apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: goapps-platform

resources:
  - base/namespace.yaml
  - base/configmap.yaml
  - services/auth/deployment.yaml
  - services/auth/service.yaml
  - services/metadata/deployment.yaml
  - services/metadata/service.yaml
  - services/runtime/deployment.yaml
  - services/runtime/service.yaml
  - services/connector/deployment.yaml
  - services/connector/service.yaml
  - services/publish/deployment.yaml
  - services/publish/service.yaml
  - services/environment/deployment.yaml
  - services/environment/service.yaml
  - services/audit/deployment.yaml
  - services/audit/service.yaml
  - services/search/deployment.yaml
  - services/search/service.yaml

commonLabels:
  app.kubernetes.io/part-of: goapps-platform
  app.kubernetes.io/managed-by: kustomize
