DROP POLICY IF EXISTS connectors_tenant_isolation ON connectors;
ALTER TABLE connectors NO FORCE ROW LEVEL SECURITY;
ALTER TABLE connectors DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS formulas_tenant_isolation ON formulas;
ALTER TABLE formulas NO FORCE ROW LEVEL SECURITY;
ALTER TABLE formulas DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS controls_tenant_isolation ON controls;
ALTER TABLE controls NO FORCE ROW LEVEL SECURITY;
ALTER TABLE controls DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS screens_tenant_isolation ON screens;
ALTER TABLE screens NO FORCE ROW LEVEL SECURITY;
ALTER TABLE screens DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS environments_tenant_isolation ON environments;
ALTER TABLE environments NO FORCE ROW LEVEL SECURITY;
ALTER TABLE environments DISABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS applications_tenant_isolation ON applications;
ALTER TABLE applications NO FORCE ROW LEVEL SECURITY;
ALTER TABLE applications DISABLE ROW LEVEL SECURITY;
