apiVersion: v1
kind: Service
metadata:
  name: metadata-service
  namespace: goapps-platform
spec:
  selector:
    app.kubernetes.io/name: metadata-service
  ports:
    - port: 8082
      targetPort: http
