apiVersion: v1
kind: Service
metadata:
  name: environment-service
  namespace: goapps-platform
spec:
  selector:
    app.kubernetes.io/name: environment-service
  ports:
    - port: 8086
      targetPort: http
